### ISSUE TITLE
PostgreSQL support?

### ISSUE THREAD

**Issue by alex-ondrus** [chi2labs/moodleR#8]
When running
``` mdl_con <- mdl_get_connection(use_cache = FALSE) ```
I receive the following error:
``` Error: Failed to connect: Lost connection to server at 'handshake: reading initial communication packet', system error: 2```
We have set up the config.yml file as described in the setup vignette and are able to connect to the database using other tools (pgAdmin III) with the same settings, so I don't think it is a connection issue. After doing some googling it looks like it may be that the package is expecting a MySQL connection. Our institute runs their Moodle database on PostgreSQL. 

Does moodleR support connections to Moodle databases running PostgreSQL?

**Comment by dietrichson** [comment]
Hello Alex,

No, we don't currently have support for Postgres. I will make a note to add
it shortly.

**Comment by alex-ondrus** [comment]
That would be amazing, thank you!

**Comment by dietrichson** [comment]
@alex-ondrus I have attempted a fix. Please note that this is **untested**, since I don't have access to a moodle database on postgres. You can try to install issue  the branch with:

devtools::install_github("chi2labs/moodleR",ref="issue_8")

I added a field `db_driver` which you can set to `postgres` and a switch inside the `get_connection` function to return a Postgres connection instead of the default. 

You can take a look at this commit:
 https://github.com/chi2labs/moodleR/commit/123e34b44d5d2455a42ea88c7f18a4e494f589f3 
to see the actual changes made, and suggest any adjustments necessary. Please let me know how it goes.

**Comment by dietrichson** [comment]
hit me up on google chat: dietrichson@gmail.com
